name: Python CI Build

on:
  push:
  workflow_dispatch:
#https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners
jobs:
  build:
    name: Build Executables
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'pip'

      - name: Upgrade setuptools, wheel, and install requirements
        run: |
          pip install --upgrade setuptools wheel pyinstaller~=5.13.2 && pip install -r requirements.txt

      - name: Build playwright
        shell: bash
        run: |
          PLAYWRIGHT_BROWSERS_PATH=0 playwright install chromium

      - name: Build Pyinstaller
        shell: bash
        run: |
          pyinstaller main.spec

      - name: Zip the Build-windows
        run: Compress-Archive -Path ./dist/MyGO.exe -DestinationPath tmp.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-windows
          path: tmp.zip
